# Generated by Django 5.0.6 on 2024-07-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('apellido', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('promedio_academico', models.FloatField()),
                ('asistencia_clases', models.IntegerField()),
                ('materias_reprobadas', models.IntegerField()),
                ('ciclo_academico', models.CharField(max_length=50)),
                ('periodo_academico', models.CharField(max_length=50)),
                ('apoyo_familiar', models.IntegerField()),
                ('situacion_socioeconomica', models.CharField(max_length=20)),
                ('trabaja', models.CharField(max_length=20)),
                ('distancia_universidad', models.CharField(max_length=20)),
            ],
        ),
    ]
