# Generated by Django 5.0.6 on 2024-07-04 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_persona_rol_delete_cuenta_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('periodo_academico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Persona',
            new_name='Usuario',
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad_desercion', models.FloatField()),
                ('probabilidad_desercion_porcentaje', models.FloatField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ciclo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.estudiante')),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.riesgo')),
            ],
        ),
    ]
