# Generated by Django 5.0.6 on 2024-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_ciclo_estudiante_riesgo_rename_persona_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='materia',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
