# Generated by Django 5.0.6 on 2024-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_estudiante_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='prediccion_desercion',
            field=models.FloatField(default=0.0),
        ),
    ]
