# Generated by Django 5.0.6 on 2024-07-21 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_rename_rol_usuario_rol_remove_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.rol')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
