# Generated by Django 5.0.6 on 2024-07-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_persona_cuenta_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediccion',
            old_name='probabilidad_desercion',
            new_name='porcentaje_futuro',
        ),
        migrations.RenameField(
            model_name='prediccion',
            old_name='probabilidad_desercion_porcentaje',
            new_name='prediccion_actual',
        ),
        migrations.RenameField(
            model_name='prediccion',
            old_name='prediccion_desercion',
            new_name='prediccion_futuro',
        ),
        migrations.RenameField(
            model_name='prediccion',
            old_name='riesgo',
            new_name='riesgo_futuro',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='materia',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ciclo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.ciclo'),
        ),
    ]
