# Generated by Django 5.0.6 on 2024-07-21 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='prediccion',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='prediccion',
            name='riesgo_futuro',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='cuenta_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cuenta_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.persona'),
        ),
        migrations.DeleteModel(
            name='Ciclo',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Prediccion',
        ),
        migrations.DeleteModel(
            name='Riesgo',
        ),
    ]
