# Generated by Django 5.0.6 on 2024-07-21 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0011_remove_prediccion_ciclo_remove_estudiante_ciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('periodo_academico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='cuentas', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cuentas_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediccion_actual', models.FloatField()),
                ('porcentaje_futuro', models.FloatField()),
                ('prediccion_futuro', models.FloatField(default=0.0)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ciclo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.estudiante')),
                ('riesgo_futuro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.riesgo')),
            ],
        ),
    ]
