# Generated by Django 5.0.6 on 2024-07-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_ciclo_riesgo_alter_cuenta_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_related', to='my_app.cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_related', to='my_app.persona'),
        ),
    ]
