# Generated by Django 5.0.6 on 2024-07-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_persona_cuenta_alter_cuenta_persona'),
        ('my_app', '0014_add_initial_roles'),
    ]

    operations = [
    ]
